### PR TITLE
Usability tweaks for the canvas.

### PR DESCRIPTION
**Pull request by Kevinpgalligan**
This adds a function called `(draw-canvas ...)` so that people don't need to include boilerplate code every time they want to draw a canvas. Also exports `canvas-width`, `canvas-height`, `image-width` and `image-height`, which I think are useful to have. Finally, it updates the canvas documentation. I left the "stars" example untouched in case it's helpful to see how to draw a canvas using lower-level functions.

Example:

```lisp
(defsketch test
      ((title "Canvas test")
       (size-scale 1))
    (let ((cv (make-canvas 2 2)))
      (canvas-paint cv +blue+ 0 0)
      (canvas-paint cv +red+ 0 1)
      (canvas-paint cv +green+ 1 0)
      (canvas-paint cv +white+ 1 1)
      (canvas-lock cv)
      (let ((draw-size (* size-scale 2)))
        (draw-canvas cv :width draw-size :height draw-size
                     :min-filter :linear :mag-filter :linear)))
    (setf size-scale (mod (1+ size-scale) 50)))
```

(I'm not sure how the min & mag filters are supposed to work, but even when I pass `:nearest`, it still looks like a linear interpolation between the colours).

### CODE REVIEW

**Comment by Kevinpgalligan** [comment]
Woops, I accidentally included my documentation update in this. I'll fix that tomorrow.

**Comment by Gleefre** [comment]
> I'm not sure how the min & mag filters are supposed to work

Those should be passed to `canvas-lock`, as they are not updated when image is locked.

**Comment by Kevinpgalligan** [comment]
Okay, I've removed the accidental commit. Also confirmed that passing `:min-filter` and `:mag-filter` to `(canvas-lock ...)` gets it to behave in the expected way, and updated the documentation of `(draw-canvas ...)` to make that usage more clear.

**Comment by vydd** [comment]
@Kevinpgalligan sorry for not asking earlier; it looks that we'll now have three ways of drawing things:

`DRAW` method that sketch classes are using (normally not overriden)
`IMAGE` for drawing images
`DRAW-CANVAS` coming from this PR

--- do you think all of these could use `DRAW`? (we could make it work for images in a separate PR and still support the old API for compat)

**Comment by Kevinpgalligan** [comment]
Hmm, I think I can de-duplicate the code that is shared between `IMAGE` and `DRAW-CANVAS`. I'm not sure that I see how `DRAW` is related, though? From my understanding, it's a method that each sketch implements that is called once per drawing loop. Within the `DRAW` method, i.e. the sketch body, we use functions like `IMAGE`, `DRAW-CANVAS`, `RECT`, `LINE`, etc. to draw actual shapes or objects. I'm not sure how they can be unified with `DRAW` or if it would make sense to do so, unless you're referring to a different `DRAW` interface.

**Comment by vydd** [comment]
@Kevinpgalligan `DRAW` is [already defined](https://github.com/vydd/sketch/blob/master/src/sketch.lisp#L87-L90) with `&allow-extra-keys`. It's already [used with figures](https://github.com/vydd/sketch/blob/master/src/figures.lisp#L14), but figures need a big revamp before they are useful.

**Comment by Kevinpgalligan** [comment]
I like your suggestion, so`DRAW` is now used to draw the canvas. Updated the corresponding part of the docs. Also added a TODO so that we don't forget to refactor when adding a `DRAW` method for images. I'm happy to do that myself once this pull request has been merged.

**Comment by vydd** [comment]
Thanks!

**Comment by aykaramba** [comment]
Aha! So this is how canvas is used:

```
(defsketch test
      ((title "Canvas test")
       (size-scale 1))
    (let ((cv (make-canvas 2 2)))
      (canvas-paint cv +blue+ 0 0)
      (canvas-paint cv +red+ 0 1)
      (canvas-paint cv +green+ 1 0)
      (canvas-paint cv +white+ 1 1)
      (canvas-lock cv)
      (let ((draw-size (* size-scale 2)))
        (draw cv :width draw-size :height draw-size
                     :min-filter :linear :mag-filter :linear)))
    (setf size-scale (mod (1+ size-scale) 50)))
```

Just had to change draw-canvas to draw. Nice.

Thx for the example and updates.

**Pull request merged**
