### PR TITLE
Make it possible to specify :min-filter or :mag-filter on image creation [ new feature ]

### PR DESCRIPTION
**Pull request by Gleefre**
Maybe needs further work to check that arguments provided are valid names for corresponding filters, but it works :)
Maybe should be also provided for the canvas?

(Reason: I want to be able to use pixel graphics, which looks ugly with the default mag-filter.)

### CODE REVIEW

**Comment by vydd** [comment]
Thanks! It would be great to have this for the canvas as well, yes.

**Comment by vydd** [comment]
(it would be nice to have these things documented too, but it would be a bit unfair to insist on it as I haven't updated docs myself in ages)

**Comment by Gleefre** [comment]
I have plans on updating documentation at some point - but I'd like to do actual work first (like this one).
And there is also the Lisp Game Jam going on right now, so I'm kind of preferring to delay adding the documentation.

**Comment by Gleefre** [comment]
On canvases: I'm not sure how to go about that: The most natural place for it would be the argument to `canvas-image`, but I don't know what should happen if the user pass another filter after the canvas was locked.

**Pull request merged**
